const FOLDER_MEDIA={
 '1BhBZrLhUP7njMcno0tf4LsR8k0P4Xh8S':['1ie05txKtu6CwSvYFbHbRZrIqpxXMYILQ','1KRsrC-dghPy67XBR7oEqvbMOIdbHmkH1','148GDlPZWui_07ZqKUAyhUSNAsXsRxT6J','14qXYbZGLDnsW1sejnIBF9ozMC3InDlD-'],
 '1TeUykB1ens1St7hJy0cOF4LROpbO9ogY':['1nyN1QqMANqrzjrOQxiM3rFHLyu-UWg22','1qn-r3Kd7kUpZHcXIvKJ434Gbgk7D0HzP','1XNhuEKVCkg2cxVpjec1cQbBBHRMQyBNp','1QyoVTPPE7SA5Kj-RYpzlYU-TJRCY8jGF'],
 '1tc4hTALKAl0AXTFrPY8k_XSbSwDmOIUx':['1ddtUB2yPRXiw7fw5PqmoyzWgbZ0Z6Dpq','1vErLfzustHfkNrOykLIMXBQr4vRubm_i','1Z9Dj9aCN0Xgwg57GI1ijJWZ0mFmh2vtG','10jZHs91dpN6xJoy1XhlWQrR3h-3OjQA1']
};
let mediaItems=[],mediaIndex=0,mediaTimer=null;
document.addEventListener('DOMContentLoaded',()=>setTimeout(enhancePortfolio,1500));
function enhancePortfolio(){addMissingCards();bindSlideshows();let c=document.getElementById('mediaClose');if(c)c.onclick=closeMedia;let p=document.getElementById('mediaPrev');if(p)p.onclick=()=>showMedia(mediaIndex-1);let n=document.getElementById('mediaNext');if(n)n.onclick=()=>showMedia(mediaIndex+1);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMedia()})}
function addMissingCards(){ensureCards('developmentGrid',[cardHTML('Educational Manuals','Instructional Support','Manuals, guides, and structured academic support material prepared for schools and teachers.','148GDlPZWui_07ZqKUAyhUSNAsXsRxT6J','1BhBZrLhUP7njMcno0tf4LsR8k0P4Xh8S'),cardHTML('School Support Resources','Academic Planning','Planning formats, support material, and institutional resources developed for schools.','14qXYbZGLDnsW1sejnIBF9ozMC3InDlD-','1BhBZrLhUP7njMcno0tf4LsR8k0P4Xh8S')]);ensureCards('digitalGrid',[cardHTML('Online Learning Media','Digital Learning','Selected educational visuals and online learning content presented as a professional media showcase.','1XNhuEKVCkg2cxVpjec1cQbBBHRMQyBNp','1TeUykB1ens1St7hJy0cOF4LROpbO9ogY'),cardHTML('Creative Campaigns','Digital Media','Official educational campaign visuals, announcements, and community engagement designs.','1QyoVTPPE7SA5Kj-RYpzlYU-TJRCY8jGF','1TeUykB1ens1St7hJy0cOF4LROpbO9ogY')]);ensureCards('trainingGrid',[cardHTML('Teacher Development','Capacity Building','Training highlights, workshop visuals, and teacher support resources prepared by R&D.','1ddtUB2yPRXiw7fw5PqmoyzWgbZ0Z6Dpq','1tc4hTALKAl0AXTFrPY8k_XSbSwDmOIUx'),cardHTML('Workshop Resources','Training Support','Selected workshop material and professional learning visuals for school teams.','1vErLfzustHfkNrOykLIMXBQr4vRubm_i','1tc4hTALKAl0AXTFrPY8k_XSbSwDmOIUx'),cardHTML('Classroom Practice','Teaching Skills','Practical classroom-support visuals and activity-based learning references.','1Z9Dj9aCN0Xgwg57GI1ijJWZ0mFmh2vtG','1tc4hTALKAl0AXTFrPY8k_XSbSwDmOIUx'),cardHTML('Learning Sessions','Professional Growth','Capacity-building sessions and learning activities documented for portfolio presentation.','10jZHs91dpN6xJoy1XhlWQrR3h-3OjQA1','1tc4hTALKAl0AXTFrPY8k_XSbSwDmOIUx')]);ensureCards('competitionsGrid',[cardHTML('Award Highlights','Student Achievement','Selected award visuals and result presentations from student programs.','1ie05txKtu6CwSvYFbHbRZrIqpxXMYILQ','1BhBZrLhUP7njMcno0tf4LsR8k0P4Xh8S'),cardHTML('Creative Activities','Learning Events','Competition-related creative activities and student learning highlights.','1KRsrC-dghPy67XBR7oEqvbMOIdbHmkH1','1BhBZrLhUP7njMcno0tf4LsR8k0P4Xh8S')])}
function ensureCards(gridId,cards){let grid=document.getElementById(gridId);if(!grid)return;let real=[...grid.children].filter(x=>!x.classList.contains('empty-state')).length;let i=0;while(real<4&&i<cards.length){grid.insertAdjacentHTML('beforeend',cards[i]);real++;i++}}
function cardHTML(title,cat,desc,fileId,folderId){return '<article class="card"><img class="card-image" src="https://drive.google.com/thumbnail?id='+fileId+'&sz=w1200" alt="'+esc(title)+'" loading="lazy"><h3>'+esc(title)+'</h3><div class="meta"><span>'+esc(cat)+'</span></div><p>'+esc(desc)+'</p><div class="card-actions"><a class="btn secondary" href="https://drive.google.com/drive/folders/'+folderId+'">View Slideshow</a></div></article>'}
function bindSlideshows(){document.querySelectorAll('a[href*="drive.google.com/drive/folders/"]').forEach(a=>{const m=a.href.match(/folders\/([^/?#]+)/);const id=m?m[1]:'';if(!id||a.dataset.ready)return;a.dataset.ready='1';a.removeAttribute('target');a.textContent='View Slideshow';a.addEventListener('click',e=>{e.preventDefault();openFolderSlideshow(id,closestTitle(a))})})}
function closestTitle(el){let card=el.closest('.card');return card&&card.querySelector('h3')?card.querySelector('h3').textContent.trim():'Portfolio Slideshow'}
function openFolderSlideshow(folderId,title){let ids=FOLDER_MEDIA[folderId]||[];if(!ids.length)return;mediaItems=ids.map((id,i)=>({src:'https://drive.google.com/thumbnail?id='+id+'&sz=w1600',title:title,caption:'Image '+(i+1)+' of '+ids.length}));mediaIndex=0;let modal=document.getElementById('mediaModal');if(modal){modal.classList.add('is-open');modal.setAttribute('aria-hidden','false')}showMedia(0);clearInterval(mediaTimer);mediaTimer=setInterval(()=>showMedia(mediaIndex+1),4500)}
function showMedia(i){if(!mediaItems.length)return;mediaIndex=(i+mediaItems.length)%mediaItems.length;let item=mediaItems[mediaIndex];let img=document.getElementById('mediaSlideImage');if(img)img.src=item.src;let t=document.getElementById('mediaSlideTitle');if(t)t.textContent=item.title;let cap=document.getElementById('mediaSlideCaption');if(cap)cap.textContent=item.caption;let count=document.getElementById('mediaCounter');if(count)count.textContent=(mediaIndex+1)+' / '+mediaItems.length}
function closeMedia(){let modal=document.getElementById('mediaModal');if(modal){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true')}clearInterval(mediaTimer)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
