const FOLDER_MEDIA={
 '1BhBZrLhUP7njMcno0tf4LsR8k0P4Xh8S':['1ie05txKtu6CwSvYFbHbRZrIqpxXMYILQ','1KRsrC-dghPy67XBR7oEqvbMOIdbHmkH1','148GDlPZWui_07ZqKUAyhUSNAsXsRxT6J','14qXYbZGLDnsW1sejnIBF9ozMC3InDlD-'],
 '1gS7PyB1a6uNKclmt0PxZO6mZrQM-X0MX':['1JGqqpK2gS1SeMREPyppO-dpBo0M1bdba','1NKtf1MBx-p4wu0GUK_2ATIcd3rWMo-L5','1Q3llvotrjPgZXzCL1YNaggjcnQ50xUSm','1wfLf0Jfe2qDyIQKalDR-Q9PKQ8NddETZ','1byWD8BmxfW0UnhCvQnwaovar7FgwKPgE','1plz7jiYvqKIzFHp5zer2q1UUx-Klsyyf'],
 '1dJim5Vugv2Fvj3p2KMvYzdSSdAs4Qw_b':['154Ye-yq4HJTvLc054zrvJsXmbav1_OgV','1V2TM783wB7ZuVnttFBNyd3o3xhxi9ayW','1f8YCm_1LoAPPi3hZO1YdVThSHu1n4RJw','1YzTX0I4gm9KHLI4MIiOb-WVGxDJ9VFqH','1QHkZkFgMnBZj0R5KqaD9Zav-phnB_Ykh','1OoNel4dUJz_tEhhVuRG8eMWztQOgrsbY'],
 '1tc4hTALKAl0AXTFrPY8k_XSbSwDmOIUx':['1ddtUB2yPRXiw7fw5PqmoyzWgbZ0Z6Dpq','1vErLfzustHfkNrOykLIMXBQr4vRubm_i','1Z9Dj9aCN0Xgwg57GI1ijJWZ0mFmh2vtG','10jZHs91dpN6xJoy1XhlWQrR3h-3OjQA1'],
 '1jLq0b3orkXAH06bSejHUExTwIBCc0Rph':[]
};
const FOLDER_LABELS={
 '1BhBZrLhUP7njMcno0tf4LsR8k0P4Xh8S':{name:'Academic Development Portfolio',cat:'Academic Development',desc:'Calendars, study-circle material, manuals, planning resources, and school-support visuals prepared by the R&D Department.'},
 '1gS7PyB1a6uNKclmt0PxZO6mZrQM-X0MX':{name:'Educational Video Channel',cat:'YouTube Learning Media',desc:'A visual showcase of educational video thumbnails, learning topics, science lessons, digital literacy content, and student-support media.'},
 '1dJim5Vugv2Fvj3p2KMvYzdSSdAs4Qw_b':{name:'E-Taleem Social Media Posts',cat:'Facebook & Social Campaigns',desc:'Selected E-Taleem posts, awareness designs, announcements, learning campaigns, and official social media visuals.'},
 '1tc4hTALKAl0AXTFrPY8k_XSbSwDmOIUx':{name:'Student Competitions Portfolio',cat:'Student Achievement',desc:'Competition posters, result announcements, award highlights, and creative student-achievement visuals organized as a gallery.'},
 '1jLq0b3orkXAH06bSejHUExTwIBCc0Rph':{name:'Training Portfolio',cat:'Training & Capacity Building',desc:'Teacher training, workshops, professional development sessions, and capacity-building visuals will appear here after adding images.'}
};
let mediaItems=[],mediaIndex=0,mediaTimer=null;
document.addEventListener('DOMContentLoaded',()=>setTimeout(enhancePortfolio,1500));
function enhancePortfolio(){document.querySelectorAll('.generated-card').forEach(x=>x.remove());makeShowcase('developmentGrid','1BhBZrLhUP7njMcno0tf4LsR8k0P4Xh8S');makeShowcase('digitalGrid','1gS7PyB1a6uNKclmt0PxZO6mZrQM-X0MX');makeShowcase('digitalGrid','1dJim5Vugv2Fvj3p2KMvYzdSSdAs4Qw_b');makeShowcase('competitionsGrid','1tc4hTALKAl0AXTFrPY8k_XSbSwDmOIUx');bindSlideshows();setupModal();}
function makeShowcase(gridId,folderId){let grid=document.getElementById(gridId),info=FOLDER_LABELS[folderId],ids=FOLDER_MEDIA[folderId]||[];if(!grid||!info||document.querySelector('.folder-showcase[data-folder-id="'+folderId+'"]')||!ids.length)return;[...grid.querySelectorAll('.card')].filter(card=>card.querySelector('a[href*="'+folderId+'"]')).forEach(card=>card.remove());let a=ids.slice(0,6).map((id,i)=>'<img class="showcase-thumb '+(i==0?'is-active':'')+'" src="https://drive.google.com/thumbnail?id='+id+'&sz=w1200" alt="'+esc(info.name)+'">').join('');let box=document.createElement('article');box.className='folder-showcase';box.dataset.folderId=folderId;box.innerHTML='<div class="showcase-media">'+a+'</div><div class="showcase-copy"><span class="label">'+esc(info.cat)+'</span><h3>'+esc(info.name)+'</h3><p>'+esc(info.desc)+'</p><div class="card-actions"><a class="btn primary" href="https://drive.google.com/drive/folders/'+folderId+'">View Slideshow</a></div></div>';grid.appendChild(box);let imgs=[...box.querySelectorAll('.showcase-thumb')];let n=0;if(imgs.length>1)setInterval(()=>{imgs[n].classList.remove('is-active');n=(n+1)%imgs.length;imgs[n].classList.add('is-active')},3500)}
function bindSlideshows(){document.querySelectorAll('a[href*="drive.google.com/drive/folders/"]').forEach(a=>{let id=getFolderId(a.href);if(!id||a.dataset.ready)return;a.dataset.ready='1';a.removeAttribute('target');a.textContent='View Slideshow';a.onclick=e=>{e.preventDefault();openFolderSlideshow(id)}})}
function setupModal(){let c=document.getElementById('mediaClose');if(c){c.innerHTML='&times;';c.onclick=closeMedia}let p=document.getElementById('mediaPrev');if(p)p.onclick=()=>showMedia(mediaIndex-1);let n=document.getElementById('mediaNext');if(n)n.onclick=()=>showMedia(mediaIndex+1);let m=document.getElementById('mediaModal');if(m)m.onclick=e=>{if(e.target===m)closeMedia()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMedia()})}
function getFolderId(url){let m=String(url||'').match(/folders\/([^/?#]+)/);return m?m[1]:''}
function openFolderSlideshow(folderId){let ids=FOLDER_MEDIA[folderId]||[],info=FOLDER_LABELS[folderId]||{name:'Portfolio Slideshow',desc:''};if(!ids.length)return;mediaItems=ids.map((id,i)=>({src:'https://drive.google.com/thumbnail?id='+id+'&sz=w1600',title:info.name,caption:info.desc+' — Image '+(i+1)+' of '+ids.length}));mediaIndex=0;let m=document.getElementById('mediaModal');if(m){m.classList.add('is-open');m.setAttribute('aria-hidden','false')}showMedia(0);clearInterval(mediaTimer);mediaTimer=setInterval(()=>showMedia(mediaIndex+1),4500)}
function showMedia(i){if(!mediaItems.length)return;mediaIndex=(i+mediaItems.length)%mediaItems.length;let item=mediaItems[mediaIndex];let img=document.getElementById('mediaSlideImage');if(img)img.src=item.src;let t=document.getElementById('mediaSlideTitle');if(t)t.textContent=item.title;let cap=document.getElementById('mediaSlideCaption');if(cap)cap.textContent=item.caption;let count=document.getElementById('mediaCounter');if(count)count.textContent=(mediaIndex+1)+' / '+mediaItems.length}
function closeMedia(){let m=document.getElementById('mediaModal');if(m){m.classList.remove('is-open');m.setAttribute('aria-hidden','true')}clearInterval(mediaTimer)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
