const SPREADSHEET_ID='15o08L1BaK0SfPdQzJu8uTCypflCAFjvPpU3XWXaNSdY';
const SHEETS={Settings:'Settings',Team:'Team',Development:'Development',DigitalProjects:'Digital Projects',Training:'Training',Competitions:'Competitions',Publications:'Publications',Resources:'Resources',Gallery:'Gallery',Contact:'Contact'};
const SITE_DEFAULTS={whatsappNumber:'923331211244',whatsappDisplay:'+92 333 1211244',youtube:'https://www.youtube.com/@etaleem9788',facebook:'https://www.facebook.com/GETetaleem/'};
const PLACEHOLDER_WORDS=['paste drive image link','paste image link','paste drive link','image link','photo link','cover image','enter image','add image','n/a','na','none','-'];
let allActivePublications=[];
document.addEventListener('DOMContentLoaded',init);
async function init(){setupNavigation();setYear();const data=await loadAllData();applySettings(data.Settings||[]);renderTeam(data.Team||[]);renderDevelopment(data.Development||[]);renderDigitalProjects(data[SHEETS.DigitalProjects]||[]);renderTraining(data.Training||[]);renderCompetitions(data.Competitions||[]);renderPublications(data.Publications||[]);renderResources(data.Resources||[]);renderGallery(data.Gallery||[]);applyContact(data.Contact||[])}
function setupNavigation(){const t=document.getElementById('navToggle'),n=document.getElementById('mainNav');if(!t||!n)return;t.addEventListener('click',()=>{const o=n.classList.toggle('is-open');t.setAttribute('aria-expanded',String(o))});n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{n.classList.remove('is-open');t.setAttribute('aria-expanded','false')}))}
function setYear(){const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear()}
async function loadAllData(){const s=document.getElementById('dataStatus'),data={};try{await Promise.all(Object.values(SHEETS).map(async name=>{data[name]=await fetchSheet(name)}));if(s)s.textContent='Live Google Sheet data connected.';return data}catch(e){console.warn('Sheet fetch issue:',e);if(s)s.textContent='Live data connection issue. Please check Google Sheet sharing/publishing.';return{Settings:[],Team:[],Development:[],[SHEETS.DigitalProjects]:[],Training:[],Competitions:[],Publications:[],Resources:[],Gallery:[],Contact:[]}}}
async function fetchSheet(name){const url=`https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(name)}&_=${Date.now()}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`Unable to fetch ${name}`);return csvToObjects(await r.text())}
function csvToObjects(csv){const rows=parseCSV(csv).filter(r=>r.some(c=>clean(c)));if(!rows.length)return[];const headers=rows[0].map(h=>clean(h));return rows.slice(1).map(row=>{const o={};headers.forEach((h,i)=>{if(h)o[h]=clean(row[i]||'')});return o})}
function parseCSV(csv){const rows=[];let row=[],v='',q=false;for(let i=0;i<csv.length;i++){const c=csv[i],nx=csv[i+1];if(c==='"'&&q&&nx==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(v);rows.push(row);row=[];v=''}else v+=c}if(v||row.length){row.push(v);rows.push(row)}return rows}
function clean(v){return String(v||'').trim()}
function isPlaceholder(v){const x=clean(v).toLowerCase();return !x||PLACEHOLDER_WORDS.includes(x)||x.startsWith('paste ')}
function activeRows(rows){return(rows||[]).filter(r=>clean(r.Status).toLowerCase()==='active').sort((a,b)=>Number(a['Display Order']||999)-Number(b['Display Order']||999))}
function settingsMap(rows){return activeRows(rows).reduce((m,r)=>{if(r.Field)m[r.Field]=r.Value||'';return m},{})}
function applySettings(rows){const s=settingsMap(rows);setText('brandTitle',s['Site Title']||'GEF R&D');setText('heroHeading',s['Hero Heading']||'Research & Development Department');setText('heroTagline',s['Hero Tagline']||'Creating educational resources, training systems, digital learning tools, and development initiatives for better school learning.');setText('shortIntro',s['Short Intro']||'The R&D Department of Ghazali Education Foundation supports schools, teachers, students, and parents through educational content, training resources, digital learning projects, competitions, publications, and development initiatives.');const logo=document.getElementById('siteLogo'),logoUrl=driveImage(s['Logo URL']);if(logo&&logoUrl)logo.src=logoUrl;if(document.getElementById('primaryBtn')&&s['Primary Button Text'])document.getElementById('primaryBtn').textContent=s['Primary Button Text'];if(document.getElementById('secondaryBtn')&&s['Secondary Button Text'])document.getElementById('secondaryBtn').textContent=s['Secondary Button Text']}
function applyContact(rows){const c=settingsMap(rows);setLink('youtubeLink',c['YouTube URL']||SITE_DEFAULTS.youtube);setLink('facebookLink',c['Facebook URL']||SITE_DEFAULTS.facebook);setLink('whatsappLink',c['WhatsApp Base Link']||`https://wa.me/${SITE_DEFAULTS.whatsappNumber}`);const p=document.getElementById('contactPanel');if(p)p.innerHTML=`<p><strong>Department:</strong> ${escapeHTML(c['Department Name']||'Research & Development Department')}</p><p><strong>Organization:</strong> ${escapeHTML(c.Organization||'Ghazali Education Foundation')}</p><p><strong>WhatsApp:</strong> ${escapeHTML(c['WhatsApp Number']||SITE_DEFAULTS.whatsappDisplay)}</p>${c.Email?`<p><strong>Email:</strong> ${escapeHTML(c.Email)}</p>`:''}${c['Office / Address']?`<p><strong>Office:</strong> ${escapeHTML(c['Office / Address'])}</p>`:''}`}
function setText(id,v){const e=document.getElementById(id);if(e&&v)e.textContent=v}function setLink(id,h){const e=document.getElementById(id);if(e&&h)e.href=h}
function renderTeam(rows){renderGrid('teamGrid',activeRows(rows),r=>`<article class="card team-card">${imageTag(r['Photo URL'],r.Name,'card-image')}<h3>${escapeHTML(r.Name)}</h3><div class="meta">${chip(r.Designation)}${chip(r.Education)}</div><p><strong>${escapeHTML(r['Short Bio']||'')}</strong></p><p>${escapeHTML(r['Main Responsibility']||'')}</p></article>`,'No active team records found. Add Active rows in the Team sheet.')}
function renderDevelopment(rows){renderGrid('developmentGrid',activeRows(rows),r=>standardCard({image:r['Image URL'],title:r.Title,category:r.Category,description:r['Short Description'],url:r['PDF / Folder URL'],button:r['Button Text']||'View Details'}),'No active development work is available yet.')}
function renderDigitalProjects(rows){renderGrid('digitalGrid',activeRows(rows),r=>standardCard({image:r['Image URL'],title:r['Project Title'],category:r.Category,description:r['Short Description'],url:r['Project Link'],button:r['Button Text']||'Open Project'}),'No active digital projects are available yet.')}
function renderTraining(rows){renderGrid('trainingGrid',activeRows(rows),r=>standardCard({image:r['Image URL'],title:r['Training Title'],category:r['Training Type'],extra:r.Audience,description:r['Short Description'],url:r['PDF / Folder URL'],button:r['Button Text']||'View Training',date:r['Date / Session']}),'No active training records are available yet.')}
function renderCompetitions(rows){renderGrid('competitionsGrid',activeRows(rows),r=>standardCard({image:r['Image URL'],title:r['Competition Title'],category:r.Category,extra:r.Participants,date:r.Year,description:r['Short Description'],url:r['Result PDF URL']||r['Gallery / Folder URL'],secondUrl:r['Gallery / Folder URL'],button:r['Button Text']||'View Details',secondButton:r['Gallery / Folder URL']?'Open Gallery':''}),'No active competitions are available yet.')}
function renderPublications(rows){allActivePublications=activeRows(rows);setupPublicationFilters(allActivePublications);renderFilteredPublications()}
function setupPublicationFilters(rows){const s=document.getElementById('publicationSearch'),c=document.getElementById('publicationCategoryFilter'),a=document.getElementById('publicationAvailabilityFilter');if(!s||!c||!a)return;fillSelectOptions(c,uniqueValues(rows,'Category'),'All Categories');fillSelectOptions(a,uniqueValues(rows,'Availability'),'All Availability');[s,c,a].forEach(x=>{x.oninput=renderFilteredPublications;x.onchange=renderFilteredPublications})}
function renderFilteredPublications(){const sv=clean(document.getElementById('publicationSearch')?.value).toLowerCase(),cv=clean(document.getElementById('publicationCategoryFilter')?.value).toLowerCase(),av=clean(document.getElementById('publicationAvailabilityFilter')?.value).toLowerCase();const f=allActivePublications.filter(r=>{const txt=[r['Title Name'],r.Category,r['Class / Level'],r['Short Description'],r.Price,r.Availability].map(clean).join(' ').toLowerCase();return(!sv||txt.includes(sv))&&(!cv||clean(r.Category).toLowerCase()===cv)&&(!av||clean(r.Availability).toLowerCase()===av)});renderGrid('publicationsGrid',f,publicationCard,allActivePublications.length?'No publication matches the selected search/filter.':'No active publications are available yet.')}
function publicationCard(r){const title=r['Title Name']||'Untitled Publication',price=clean(r.Price),av=clean(r.Availability)||'Availability not listed';return`<article class="card publication-card">${imageTag(r['Cover Image URL'],title,'card-image publication-cover')}<div class="publication-card-body"><h3>${escapeHTML(title)}</h3><div class="meta">${chip(r.Category)}${chip(r['Class / Level'])}</div><p>${escapeHTML(r['Short Description']||'')}</p><div class="price-row"><span><strong>Price:</strong> ${escapeHTML(displayPrice(price))}</span><span class="availability ${availabilityClass(av)}">${escapeHTML(av)}</span></div><div class="card-actions publication-actions">${actionButton(r['PDF Preview URL'],'PDF Preview','secondary')}${whatsappOrderButton(title)}</div></div></article>`}
function fillSelectOptions(sel,vals,label){const cur=sel.value;sel.innerHTML=`<option value="">${escapeHTML(label)}</option>`+vals.map(v=>`<option value="${escapeAttribute(v)}">${escapeHTML(v)}</option>`).join('');if([...sel.options].some(o=>o.value===cur))sel.value=cur}
function uniqueValues(rows,key){return[...new Set((rows||[]).map(r=>clean(r[key])).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function displayPrice(p){return!p||p.toLowerCase().startsWith('enter ')?'Not listed':p}
function availabilityClass(v){const x=clean(v).toLowerCase();if(x.includes('available')&&!x.includes('unavailable'))return'is-available';if(x.includes('out')||x.includes('unavailable'))return'is-unavailable';if(x.includes('coming'))return'is-coming';return'is-neutral'}
function whatsappOrderButton(title){const msg=`Hello R&D Team, I am interested in this publication/title: ${title}`;const href=`https://wa.me/${SITE_DEFAULTS.whatsappNumber}?text=${encodeURIComponent(msg)}`;return`<a class="btn primary order-btn" href="${escapeAttribute(href)}" target="_blank" rel="noopener" aria-label="Order ${escapeAttribute(title)} on WhatsApp">Order on WhatsApp</a>`}
function renderResources(rows){renderGrid('resourcesGrid',activeRows(rows),r=>standardCard({image:r['Image URL'],title:r['Resource Title'],category:r.Category,extra:r['File Type'],description:r['Short Description'],url:r['PDF / Folder URL'],button:r['Button Text']||'Open Resource'}),'No active resources are available yet.')}
function renderGallery(rows){const active=activeRows(rows),g=document.getElementById('galleryGrid');if(!g)return;if(!active.length){g.innerHTML='<div class="empty-state">No active gallery images are available yet.</div>';return}g.innerHTML=active.map(r=>`<article class="gallery-item">${imageTag(r['Image URL'],r['Image Title'],'')}<div class="gallery-caption"><strong>${escapeHTML(r['Image Title']||'Gallery Image')}</strong>${chip(r.Category)}<p>${escapeHTML(r['Short Caption']||'')}</p></div></article>`).join('')}
function standardCard({image,title,category,extra,date,description,url,secondUrl,button,secondButton}){return`<article class="card">${imageTag(image,title,'card-image')}<h3>${escapeHTML(title||'Untitled')}</h3><div class="meta">${chip(category)}${chip(extra)}${chip(date)}</div><p>${escapeHTML(description||'')}</p><div class="card-actions">${actionButton(url,button)}${secondUrl?actionButton(secondUrl,secondButton||'Open Link','ghost'):''}</div></article>`}
function renderGrid(id,rows,tpl,msg){const g=document.getElementById(id);if(!g)return;if(!rows.length){g.innerHTML=`<div class="empty-state">${escapeHTML(msg)}</div>`;return}g.innerHTML=rows.map(tpl).join('')}
function chip(v){return v?`<span>${escapeHTML(v)}</span>`:''}
function actionButton(url,text,style='secondary'){const u=clean(url);if(isPlaceholder(u))return'';return`<a class="btn ${style}" href="${escapeAttribute(normalizeLink(u))}" target="_blank" rel="noopener">${escapeHTML(text||'Open')}</a>`}
function imageTag(url,alt,cls=''){const src=driveImage(url),ph=placeholderImage(alt||'GEF R&D');return`<img class="${cls}" src="${escapeAttribute(src||ph)}" alt="${escapeAttribute(alt||'R&D portfolio image')}" loading="lazy" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='${ph}';" />`}
function driveImage(url){const u=clean(url);if(isPlaceholder(u)||isDriveFolder(u))return'';const id=getDriveFileId(u);if(id)return`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1200`;return u}
function isDriveFolder(url){return/drive\.google\.com\/drive\/folders\//i.test(clean(url))}
function getDriveFileId(url){const u=clean(url);const ps=[/\/file\/d\/([^/?#]+)/,/[?&]id=([^&#]+)/,/thumbnail\?[^#]*[?&]?id=([^&#]+)/];for(const p of ps){const m=u.match(p);if(m?.[1])return decodeURIComponent(m[1])}return''}
function normalizeLink(url){return isPlaceholder(url)?'':clean(url)}
function placeholderImage(label){const text=encodeURIComponent(label||'GEF R&D');return`data:image/svg+xml;charset=UTF-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='900' height='600' viewBox='0 0 900 600'%3E%3Crect width='900' height='600' fill='%23fff8ea'/%3E%3Crect x='42' y='42' width='816' height='516' rx='34' fill='%23ffffff' stroke='%237a1114' stroke-opacity='.20'/%3E%3Ccircle cx='450' cy='245' r='88' fill='%23f5b51b' fill-opacity='.35'/%3E%3Ctext x='450' y='340' text-anchor='middle' font-family='Arial, sans-serif' font-size='44' font-weight='700' fill='%237a1114'%3E${text}%3C/text%3E%3Ctext x='450' y='395' text-anchor='middle' font-family='Arial, sans-serif' font-size='24' fill='%236f6262'%3EResearch %26 Development%3C/text%3E%3C/svg%3E`}
function escapeHTML(v){return String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}function escapeAttribute(v){return escapeHTML(v).replaceAll('`','&#096;')}
